#!/bin/bash

if [ -n "$1" ]; then
sz=`ls out/$1 | wc -w`

rm -rf svg/$1
mkdir -p svg/$1

cargo run --release --bin vis in/$1.txt out/result/$1.txt svg/$1/$sz.svg > score/$1.txt

for((i=0;i<$sz;i++))
do
cargo run --release --bin vis in/$1.txt out/$1/$i.txt svg/$1/$i.svg > /dev/null 2>&1
done


fi
